name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Cache Dependencies
        run: cargo --version

      # - name: Install
      #   run: bash -c "cd crates/binding_core_wasm && wasm-pack build --out-name wasm --release --scope=swc --target web && rm pkg/{.gitignore,package.json}"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "streif"
          entrypoint: "./server.ts"
