name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Install
        run: ./build.sh

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "streif"
          entrypoint: "./server.ts"
